stages:
  - compile
  - build

compile:
  stage: compile
  image: node:8.15-alpine
  script:
    - yarn global add node-sass
    - node-sass ./themes/Uxcalibur/assets/sass/style.scss ./themes/Uxcalibur/static/css/style.min.css --style compressed
  only:
    - master
  artifacts:
    paths:
      - ./themes/Uxcalibur/static/css/style.min.css

build:
  stage: build
  image: registry.gitlab.com/pages/hugo:latest
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - hugo
  artifacts:
    paths:
      - public
  only:
    - master
