baseURL = "/"
languageCode = "en-us"
title = "UXCalibur"
theme = "Uxcalibur"
enableRobotsTXT = true
googleAnalytics = "UA-23456303-7"

[permalinks]
  portfolio = "portfolio/:filename"
  page = "/:filename"

[params]
    absUrl = "https://beta.goncaloandrade.com"
    Tagline = "UX, Product, Digital Design"
    Description = "Portfolio and work by Goncalo Andrade, UX designer"
    dateFormat = "2 Jan, 2006"

[menu]
  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
  [[menu.main]]
    name = "Home"
    url = "/"
  [[menu.main]]
    name = "About me"
    url = "/about-me"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5